apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: aegis-app
description: AEGIS Governance delivery pipeline

serialPipeline:
  stages:
    - targetId: prod
      profiles:
        - prod

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Production GKE target

gke:
  cluster: projects/aegis-gov-prod/locations/us-central1/clusters/aegis-cluster
