import crypto from "node:crypto";
import type { DocumentRecord, AuthorityChainRecord } from "../../models/domain.js";
import { db } from "../../store/governance-store.js";

function nowIso() {
  return new Date().toISOString();
}

export function buildComplianceDisclaimer(packetType: string, trustName: string, jurisdiction: string) {
  return [
    "PLATFORM COMPLIANCE DISCLAIMER",
    `${trustName} / ${packetType.toUpperCase()} / ${jurisdiction}`,
    "",
    "This export bundle was generated by an administrative workflow and evidentiary support system.",
    "It organizes records, manifests, timestamps, signatures, and repository metadata for review.",
    "",
    "The software does not determine legal sufficiency, statutory compliance, filing validity, service validity, jurisdictional compliance, admissibility, or enforceability.",
    "Users remain responsible for independent legal, tax, fiduciary, and jurisdiction-specific review before relying on any record or packet externally.",
  ].join("\n");
}

export function createAuthorityRecord(document: DocumentRecord): AuthorityChainRecord {
  const controlling = db.documents.find((item) => item.docType === "governing" && item.governingLevel === "controlling" && !item.deletedAt) || null;
  const isGoverning = document.docType === "governing";
  const status: AuthorityChainRecord["status"] = isGoverning && controlling && controlling.id !== document.id && document.governingLevel === "controlling" ? "invalid" : "valid";
  return {
    id: crypto.randomUUID(),
    trustId: document.trustId,
    documentId: document.id,
    authorityType: isGoverning ? "governing-instrument" : "derived-instrument",
    parentDocumentId: isGoverning ? null : controlling?.id || null,
    status,
    validatedAt: nowIso(),
    notes: status === "invalid"
      ? "Controlling governing level is locked to the first active governing instrument."
      : "Authority chain validated against controlling instrument hierarchy.",
  };
}
