apiVersion: v1
kind: Service
metadata:
  name: aegis-frontend
  namespace: aegis
spec:
  selector:
    app: aegis-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
