apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-frontend
  namespace: aegis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aegis-frontend
  template:
    metadata:
      labels:
        app: aegis-frontend
    spec:
      nodeSelector:
        cloud.google.com/compute-class: web-flex
      containers:
        - name: frontend
          image: frontend
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"