DROP INDEX IF EXISTS idx_approvals_target;
DROP INDEX IF EXISTS idx_packets_trust_status_version;
DROP INDEX IF EXISTS idx_distributions_trust_status_version;
DROP TABLE IF EXISTS approvals;
ALTER TABLE packets DROP COLUMN IF EXISTS version_no;
ALTER TABLE packets DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE packets DROP COLUMN IF EXISTS immutable;
ALTER TABLE packets DROP COLUMN IF EXISTS hash_anchor_receipt;
ALTER TABLE packets DROP COLUMN IF EXISTS anchored_at;
ALTER TABLE packets DROP COLUMN IF EXISTS export_watermark;
ALTER TABLE packets DROP COLUMN IF EXISTS verification_summary_path;
ALTER TABLE packets DROP COLUMN IF EXISTS manifest_key_id;
ALTER TABLE packets DROP COLUMN IF EXISTS timestamp_authority;
ALTER TABLE packets DROP COLUMN IF EXISTS timestamp_token;
ALTER TABLE packets DROP COLUMN IF EXISTS timestamp_path;
ALTER TABLE packets DROP COLUMN IF EXISTS bundle_hash;
ALTER TABLE packets DROP COLUMN IF EXISTS manifest_hash;
ALTER TABLE packets DROP COLUMN IF EXISTS bundle_signature;
ALTER TABLE packets DROP COLUMN IF EXISTS manifest_signature;
ALTER TABLE packets DROP COLUMN IF EXISTS bundle_path;
ALTER TABLE packets DROP COLUMN IF EXISTS bundle_dir;
ALTER TABLE packets DROP COLUMN IF EXISTS approval_count;
ALTER TABLE packets DROP COLUMN IF EXISTS required_approvals;
ALTER TABLE packets DROP COLUMN IF EXISTS notes;
ALTER TABLE packets DROP COLUMN IF EXISTS reason_code;
ALTER TABLE packets DROP COLUMN IF EXISTS generated_by_role;
ALTER TABLE distributions DROP COLUMN IF EXISTS version_no;
ALTER TABLE distributions DROP COLUMN IF EXISTS approval_count;
ALTER TABLE distributions DROP COLUMN IF EXISTS required_approvals;
ALTER TABLE distributions DROP COLUMN IF EXISTS reason_code;
ALTER TABLE distributions DROP COLUMN IF EXISTS requested_by_role;
ALTER TABLE distributions DROP COLUMN IF EXISTS requested_by;
